/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package caldera;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.time.LocalDate;

class ClientTest
{
    
}
