/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package caldera;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.time.LocalDate;

class ClientTest
{
    static Server server;

    String host = "localhost";
    int port = 8889;
    String username = "jspacco";
    String key = "12345";
    Event event = new Event("D-Day", 
        "The day the Allies invaded Normandy",
        "Battle",
        LocalDate.of(1944, 6, 6),
        "Normandy, France",
        "admin",
        "history", "military"
        );

    // @BeforeAll static void setUp() throws Exception
    // {
    //     new Thread() {
    //         public void run() {
    //             try {
    //                 server = new Server(8889, "users.properties", "base-events.json");
    //                 server.run();
    //             } catch (Exception e) {
    //                 e.printStackTrace();
    //             }
    //         }
    //     }.start();
    // }

    // @AfterAll static void tearDown() throws Exception
    // {
    //     server.shutdown();
    // }

    // @Test void successfulPost() throws Exception
    // {
    //     Client.postEvent(host, port, username, key, event);
    // }

    // @Test void authenticationFailure() throws Exception
    // {
    //     assertThrows(AuthenticationException.class, 
    //         () -> Client.postEvent(host, port, username, "wrongkey", event));
    // }
}
